export const dataSekolah = [
  "SMK Negeri 1 Surakarta",
  "SMK Negeri 2 Surakarta",
  "SMK Negeri 3 Surakarta",
  "SMK Negeri 4 Surakarta",
  "SMK Negeri 5 Surakarta",
  "SMK Negeri 6 Surakarta",
  "SMK Negeri 7 Surakarta",
  "SMK Negeri 8 Surakarta",
  "SMK Negeri 9 Surakarta",
  "SMK Muhammadiyah 1 Surakarta",
  "SMK Muhammadiyah 3 Surakarta",
  "SMK Muhammadiyah 4 Surakarta",
  "SMK Batik 1 Surakarta",
  "SMK Batik 2 Surakarta",
  "SMK Kristen 1 Surakarta",
  "SMK Kristen 2 Surakarta",
  "SMK Kanisius Surakarta",
  "SMK Kristen Margoyudan Surakarta",
  "SMK Marsudirini Marganingsih Surakarta",
  "SMK Katolik St. Mikael Surakarta",
  "SMK Cokroaminoto 1 Surakarta",
  "SMK Cokroaminoto 2 Surakarta",
  "SMK Tunas Pembangunan 2 Surakarta",
  "SMK Tunas Pembangunan 3 Surakarta",
  "SMK Pancasila Surakarta",
  "SMK PGRI 2 Surakarta",
  "Balai Latihan Kerja (BLK) Surakarta",
  "SMK Kasatriyan Kraton Surakarta",
  "SMK Farmasi Nasional Surakarta",
  "SMK Sahid Surakarta",
  "SMK Tekno-SA Surakarta",
  "SMK Grafika Mandiri Surakarta",
  "SMK Empat Lima Surakarta",
  "SMK Wijaya Kusuma Surakarta",
  "SMK Purnama Surakarta",
  "SMK Al-Islam Surakarta",
  "SMK Warga Surakarta",
  "SMK Kesehatan Mandala Bhakti Surakarta",
  "SMK Bhinneka Karya Surakarta",
  "SMK Murni 1 Surakarta",
  "SMK PGRI 1 Surakarta",
  "SMK IT-Smart Informatika Surakarta",
  "SMK Santo Paulus Surakarta",
  "Universitas Slamet Riyadi",
  "Adi Unggul Bhirawa (AUB) Surakarta",
  "SMK Jaya Wisata Surakarta",
  "SMK Muh 5 Surakarta",
  "SMK Murni 2 Surakarta",
  "SLB N Surakarta",
  "Politeknik Indonusa",
  "UNS Surakarta",
  "SMK Bimando",
  "SMK Analis Kesehatan Nasional",
  "Politeknik Pratama Mulia",
  "Universitas 'Aisyiyah Surakarta",
  "Univesitas Islam Batik Surakarta",
  "Universitas Kusuma Husada Surakarta",
  "Sekolah Tinggi Pariwisata Sahid Surakarta",
  "UNIVERSITAS SETIABUDI",
  "STMIK Sinar Nusantara",
  "Politeknik Insan Husada Surakarta",
  "Politeknik ATMI Surakarta",
  "SLB D YPAC SURAKARTA",
  "SLB D1 YPAC SURAKARTA",
  "Univeristas Pignatelli Triputra"
];
